import Navbar from '@/components/Navbar';
import '@/styles/globals.css';
import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import {Toaster} from "@/components/ui/toaster";
import {Provider} from "@radix-ui/react-toast";
import {ReactNode} from "react";

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                   }: {
    children: ReactNode;
}) {
    return (
        <html lang='en'>
        <body className={inter.className}>
        <Provider>
            <main className='h-screen flex flex-col justify-center items-center'>
                <Navbar/>
                {children}
            </main>
            <Toaster/>
        </Provider>
        </body>
        </html>
    );
}
